"""publish_discovery — publish the inference-store JSON-LD to the website.

Copies inferences/discovery.jsonld to the site root (fetchable at
/discovery.jsonld) and inlines it into index.html as a second JSON-LD block
(what crawlers actually index), refreshed between markers so re-running is
idempotent. Also ensures a <link rel="alternate"> reference exists.

- Run after: build_index.py --voices --jsonld
- Idempotent: safe to run repeatedly; the inline block is replaced, not appended
"""

import sys
from pathlib import Path

INFERENCES_DIR = Path("inferences")
JSONLD = INFERENCES_DIR / "discovery.jsonld"
SITE_REPO = Path.home() / "repos" / "robolawyer-tm.github.io"

BEGIN = "  <!-- BEGIN discovery-jsonld (generated by publish_discovery.py) -->"
END = "  <!-- END discovery-jsonld -->"
LINK = ('  <link rel="alternate" type="application/ld+json" '
        'href="/discovery.jsonld" title="Inference Store Catalog">')


def publish(jsonld_path=None, site_repo=None):
    jsonld_path = Path(jsonld_path or JSONLD)
    site_repo = Path(site_repo or SITE_REPO)
    index_html = site_repo / "index.html"

    if not jsonld_path.exists():
        sys.exit(f"Not found: {jsonld_path} — run build_index.py --jsonld first")
    if not index_html.exists():
        sys.exit(f"Not found: {index_html}")

    catalog = jsonld_path.read_text().rstrip()

    # 1. Standalone copy at the site root
    dest = site_repo / "discovery.jsonld"
    dest.write_text(catalog + "\n")

    # 2. Build the inline block
    inline = '  <script type="application/ld+json">\n' + catalog + "\n  </script>"
    block = f"{BEGIN}\n{inline}\n{END}"

    html = index_html.read_text()

    # 3. Replace existing block, or insert after the first </script> in head
    if BEGIN in html and END in html:
        pre = html.split(BEGIN)[0]
        post = html.split(END, 1)[1]
        html = pre + block + post
        action = "refreshed inline block"
    else:
        marker = "  </script>\n"
        idx = html.find(marker)
        if idx == -1:
            sys.exit("Could not find an existing </script> to anchor the block")
        cut = idx + len(marker)
        html = html[:cut] + block + "\n" + html[cut:]
        action = "inserted inline block"

    # 4. Ensure the <link rel="alternate"> reference exists
    if "/discovery.jsonld" not in html.split(BEGIN)[0]:
        anchor = '<link rel="alternate" type="text/plain" href="/llms.txt"'
        if anchor in html:
            line = [l for l in html.splitlines() if anchor in l][0]
            html = html.replace(line, line + "\n" + LINK, 1)
            action += " + added <link>"

    index_html.write_text(html)

    print(f"discovery.jsonld -> {dest}")
    print(f"index.html: {action}")


if __name__ == "__main__":
    publish()

# llm: claude-opus-4-8 | 2026-06-26 | repos/vivify-inferences/publish_discovery.py | created — publish JSON-LD discovery surface to site (standalone file + idempotent inline block + link ref)
# llm: claude-opus-4-8 | 2026-06-28 | repos/vivify-operators/publish_discovery.py | ported from vivify-inferences — publish discovery JSON-LD (run-on-demand; review public/private before real-data publish)
